name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v4

    - name: Configurar entorno de Java (si tu script usa ecj/keytool)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # AQUÍ ES DONDE LO PONES:
    - name: Dar permisos de ejecución al script de compilación
      run: chmod +x build.sh

    - name: Ejecutar la compilación
      run: ./build.sh
